name: Sync Playlist from Google Drive

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # =================================================================
      # === PERINTAH DOWNLOAD BARU YANG LEBIH CANGGIH ===
      # =================================================================
      - name: Download file from Google Drive (Handles Large File Warning)
        run: |
          FILE_ID="1xfsnxaBbvzpRSnEkYWR0M0zEehlMBDNN"
          # Langkah 1: Ambil cookie konfirmasi dari Google
          curl -sc /tmp/cookies "https://docs.google.com/uc?export=download&id=${FILE_ID}" > /dev/null
          # Langkah 2: Gunakan cookie tersebut untuk mengunduh file yang sebenarnya
          curl -Lb /tmp/cookies "https://docs.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' /tmp/cookies`&id=${FILE_ID}" -o playlist_new.m3u

      # Langkah untuk memastikan unduhan berhasil
      - name: Verify Download
        run: |
          echo "Ukuran file yang diunduh: $(ls -l playlist_new.m3u | awk '{print $5}') bytes"
          if [ ! -s playlist_new.m3u ]; then
            echo "::error::File yang diunduh kosong! Proses gagal."
            exit 1
          fi
          echo "File berhasil diunduh dan tidak kosong."
          head -n 20 playlist_new.m3u
      # =================================================================

      - name: Check for changes
        id: diff
        run: |
          if ! git diff --quiet playlist.m3u playlist_new.m3u; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Commit and push if changed
        if: steps.diff.outputs.changes == 'true'
        run: |
          echo "Playlist has been updated. Committing changes..."
          mv playlist_new.m3u playlist.m3u
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add playlist.m3u
          git commit -m "Update playlist from Google Drive"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Clean up if no changes
        if: steps.diff.outputs.changes == 'false'
        run: |
          echo "No changes detected in the playlist."
          rm playlist_new.m3u
